[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/taylor-swift-l-icone-pop/"
to = "/taylor-swift-l-icone-pop-qui-fait-trembler-l-amerique-trumpiste/"

[[redirects]]
from = "/equipe/senior/"
to = "/equipe/categories/senior/"

[[redirects]]
from = "/test-1/"
to = "/taylor-swift-l-icone-pop-qui-fait-trembler-l-amerique-trumpiste/"

